version: "3"

volumes:
  postgres-data:
    driver: local
  app-gems:
    driver: local

services:
  postgres:
    image: postgres:9.6.9
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest

  backend:
    build: .
    image: chayel/signs
    command: rails server -b 0.0.0.0 -p 3000
    ports:
      - 3000:3000
    links:
      - postgres:db
      - redis
    entrypoint: /usr/src/app/development-entrypoint
    volumes:
      - .:/usr/src/app
      - app-gems:/usr/local/bundle
    stdin_open: true
    tty: true
    env_file:
      - '.env'
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/my_app_development
      RAILS_LOG_TO_STDOUT: "true"