version: 2
jobs:
  build:
    parallelism: 4
    working_directory: ~/user/src/app
    docker:
      - image: chayel/signs
        environment:
          RAILS_ENV: test
          PGUSER: circleci
#      - image: circleci/postgres:9.6.8-alpine-ram
#        environment:
#          POSTGRES_USER: circleci
    steps:
#      - checkout

#      # Restore bundle cache
#      - restore_cache:
#          key: signs-{{ checksum "Gemfile.lock" }}
#
#      # Bundle install dependencies
#      - run: bundle install --path vendor/bundle
#
#      # Store bundle cache
#      - save_cache:
#          key: signs-{{ checksum "Gemfile.lock" }}
#          paths:
#            - vendor/bundle
#
#      # Database setup
#      - run: bundle exec rake db:create
#      - run: bundle exec rake db:schema:load

      # Install sudo
      - run: apt-get install -y sudo

      # Install Docker Compose
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker

      # Run rspec in parallel
      - run: |
          docker-compose run backend rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress
      # Save test results for timing analysis
      - store_test_results:
          path: test_results