version: 2
jobs:
  build:
    parallelism: 4
    # working_directory: ~/user/src/app
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          RAILS_ENV: test
          PGUSER: circleci
          DATABASE_URL: postgres://circleci:password@localhost:5432/signs_test
      - image: circleci/postgres:9.6.9-alpine-ram
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: password
          POSTGRES_USER: your-app-name
          POSTGRES_DB: signs_test
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          key: signs-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: signs-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Run rspec in parallel
      - run: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress
      # Save test results for timing analysis
      - store_test_results:
          path: test_results